# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ariles/delivery/R-TYPE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ariles/delivery/R-TYPE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ariles/delivery/R-TYPE/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariles/delivery/R-TYPE/CMakeFiles /home/ariles/delivery/R-TYPE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariles/delivery/R-TYPE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named ecs

# Build rule for target.
ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecs
.PHONY : ecs

# fast build rule for target.
ecs/fast:
	$(MAKE) $(MAKESILENT) -f ecs/CMakeFiles/ecs.dir/build.make ecs/CMakeFiles/ecs.dir/build
.PHONY : ecs/fast

#=============================================================================
# Target rules for targets named r-type_app

# Build rule for target.
r-type_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_app
.PHONY : r-type_app

# fast build rule for target.
r-type_app/fast:
	$(MAKE) $(MAKESILENT) -f app/CMakeFiles/r-type_app.dir/build.make app/CMakeFiles/r-type_app.dir/build
.PHONY : r-type_app/fast

Server/src/ClientState.o: Server/src/ClientState.cpp.o
.PHONY : Server/src/ClientState.o

# target to build an object file
Server/src/ClientState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/ClientState.cpp.o
.PHONY : Server/src/ClientState.cpp.o

Server/src/ClientState.i: Server/src/ClientState.cpp.i
.PHONY : Server/src/ClientState.i

# target to preprocess a source file
Server/src/ClientState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/ClientState.cpp.i
.PHONY : Server/src/ClientState.cpp.i

Server/src/ClientState.s: Server/src/ClientState.cpp.s
.PHONY : Server/src/ClientState.s

# target to generate assembly for a file
Server/src/ClientState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/ClientState.cpp.s
.PHONY : Server/src/ClientState.cpp.s

Server/src/GameLogic.o: Server/src/GameLogic.cpp.o
.PHONY : Server/src/GameLogic.o

# target to build an object file
Server/src/GameLogic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameLogic.cpp.o
.PHONY : Server/src/GameLogic.cpp.o

Server/src/GameLogic.i: Server/src/GameLogic.cpp.i
.PHONY : Server/src/GameLogic.i

# target to preprocess a source file
Server/src/GameLogic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameLogic.cpp.i
.PHONY : Server/src/GameLogic.cpp.i

Server/src/GameLogic.s: Server/src/GameLogic.cpp.s
.PHONY : Server/src/GameLogic.s

# target to generate assembly for a file
Server/src/GameLogic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameLogic.cpp.s
.PHONY : Server/src/GameLogic.cpp.s

Server/src/GameServerLoop.o: Server/src/GameServerLoop.cpp.o
.PHONY : Server/src/GameServerLoop.o

# target to build an object file
Server/src/GameServerLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameServerLoop.cpp.o
.PHONY : Server/src/GameServerLoop.cpp.o

Server/src/GameServerLoop.i: Server/src/GameServerLoop.cpp.i
.PHONY : Server/src/GameServerLoop.i

# target to preprocess a source file
Server/src/GameServerLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameServerLoop.cpp.i
.PHONY : Server/src/GameServerLoop.cpp.i

Server/src/GameServerLoop.s: Server/src/GameServerLoop.cpp.s
.PHONY : Server/src/GameServerLoop.s

# target to generate assembly for a file
Server/src/GameServerLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameServerLoop.cpp.s
.PHONY : Server/src/GameServerLoop.cpp.s

Server/src/GameSession.o: Server/src/GameSession.cpp.o
.PHONY : Server/src/GameSession.o

# target to build an object file
Server/src/GameSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameSession.cpp.o
.PHONY : Server/src/GameSession.cpp.o

Server/src/GameSession.i: Server/src/GameSession.cpp.i
.PHONY : Server/src/GameSession.i

# target to preprocess a source file
Server/src/GameSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameSession.cpp.i
.PHONY : Server/src/GameSession.cpp.i

Server/src/GameSession.s: Server/src/GameSession.cpp.s
.PHONY : Server/src/GameSession.s

# target to generate assembly for a file
Server/src/GameSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/GameSession.cpp.s
.PHONY : Server/src/GameSession.cpp.s

Server/src/MessageQueue.o: Server/src/MessageQueue.cpp.o
.PHONY : Server/src/MessageQueue.o

# target to build an object file
Server/src/MessageQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/MessageQueue.cpp.o
.PHONY : Server/src/MessageQueue.cpp.o

Server/src/MessageQueue.i: Server/src/MessageQueue.cpp.i
.PHONY : Server/src/MessageQueue.i

# target to preprocess a source file
Server/src/MessageQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/MessageQueue.cpp.i
.PHONY : Server/src/MessageQueue.cpp.i

Server/src/MessageQueue.s: Server/src/MessageQueue.cpp.s
.PHONY : Server/src/MessageQueue.s

# target to generate assembly for a file
Server/src/MessageQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/MessageQueue.cpp.s
.PHONY : Server/src/MessageQueue.cpp.s

Server/src/Protocole.o: Server/src/Protocole.cpp.o
.PHONY : Server/src/Protocole.o

# target to build an object file
Server/src/Protocole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Protocole.cpp.o
.PHONY : Server/src/Protocole.cpp.o

Server/src/Protocole.i: Server/src/Protocole.cpp.i
.PHONY : Server/src/Protocole.i

# target to preprocess a source file
Server/src/Protocole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Protocole.cpp.i
.PHONY : Server/src/Protocole.cpp.i

Server/src/Protocole.s: Server/src/Protocole.cpp.s
.PHONY : Server/src/Protocole.s

# target to generate assembly for a file
Server/src/Protocole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Protocole.cpp.s
.PHONY : Server/src/Protocole.cpp.s

Server/src/StartServer.o: Server/src/StartServer.cpp.o
.PHONY : Server/src/StartServer.o

# target to build an object file
Server/src/StartServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/StartServer.cpp.o
.PHONY : Server/src/StartServer.cpp.o

Server/src/StartServer.i: Server/src/StartServer.cpp.i
.PHONY : Server/src/StartServer.i

# target to preprocess a source file
Server/src/StartServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/StartServer.cpp.i
.PHONY : Server/src/StartServer.cpp.i

Server/src/StartServer.s: Server/src/StartServer.cpp.s
.PHONY : Server/src/StartServer.s

# target to generate assembly for a file
Server/src/StartServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/StartServer.cpp.s
.PHONY : Server/src/StartServer.cpp.s

Server/src/Tcpserver.o: Server/src/Tcpserver.cpp.o
.PHONY : Server/src/Tcpserver.o

# target to build an object file
Server/src/Tcpserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Tcpserver.cpp.o
.PHONY : Server/src/Tcpserver.cpp.o

Server/src/Tcpserver.i: Server/src/Tcpserver.cpp.i
.PHONY : Server/src/Tcpserver.i

# target to preprocess a source file
Server/src/Tcpserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Tcpserver.cpp.i
.PHONY : Server/src/Tcpserver.cpp.i

Server/src/Tcpserver.s: Server/src/Tcpserver.cpp.s
.PHONY : Server/src/Tcpserver.s

# target to generate assembly for a file
Server/src/Tcpserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/Tcpserver.cpp.s
.PHONY : Server/src/Tcpserver.cpp.s

Server/src/UdpProtocole.o: Server/src/UdpProtocole.cpp.o
.PHONY : Server/src/UdpProtocole.o

# target to build an object file
Server/src/UdpProtocole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpProtocole.cpp.o
.PHONY : Server/src/UdpProtocole.cpp.o

Server/src/UdpProtocole.i: Server/src/UdpProtocole.cpp.i
.PHONY : Server/src/UdpProtocole.i

# target to preprocess a source file
Server/src/UdpProtocole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpProtocole.cpp.i
.PHONY : Server/src/UdpProtocole.cpp.i

Server/src/UdpProtocole.s: Server/src/UdpProtocole.cpp.s
.PHONY : Server/src/UdpProtocole.s

# target to generate assembly for a file
Server/src/UdpProtocole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpProtocole.cpp.s
.PHONY : Server/src/UdpProtocole.cpp.s

Server/src/UdpServer.o: Server/src/UdpServer.cpp.o
.PHONY : Server/src/UdpServer.o

# target to build an object file
Server/src/UdpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpServer.cpp.o
.PHONY : Server/src/UdpServer.cpp.o

Server/src/UdpServer.i: Server/src/UdpServer.cpp.i
.PHONY : Server/src/UdpServer.i

# target to preprocess a source file
Server/src/UdpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpServer.cpp.i
.PHONY : Server/src/UdpServer.cpp.i

Server/src/UdpServer.s: Server/src/UdpServer.cpp.s
.PHONY : Server/src/UdpServer.s

# target to generate assembly for a file
Server/src/UdpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/UdpServer.cpp.s
.PHONY : Server/src/UdpServer.cpp.s

Server/src/main.o: Server/src/main.cpp.o
.PHONY : Server/src/main.o

# target to build an object file
Server/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/main.cpp.o
.PHONY : Server/src/main.cpp.o

Server/src/main.i: Server/src/main.cpp.i
.PHONY : Server/src/main.i

# target to preprocess a source file
Server/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/main.cpp.i
.PHONY : Server/src/main.cpp.i

Server/src/main.s: Server/src/main.cpp.s
.PHONY : Server/src/main.s

# target to generate assembly for a file
Server/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/Server/src/main.cpp.s
.PHONY : Server/src/main.cpp.s

ecs/src/registery.o: ecs/src/registery.cpp.o
.PHONY : ecs/src/registery.o

# target to build an object file
ecs/src/registery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/ecs/src/registery.cpp.o
.PHONY : ecs/src/registery.cpp.o

ecs/src/registery.i: ecs/src/registery.cpp.i
.PHONY : ecs/src/registery.i

# target to preprocess a source file
ecs/src/registery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/ecs/src/registery.cpp.i
.PHONY : ecs/src/registery.cpp.i

ecs/src/registery.s: ecs/src/registery.cpp.s
.PHONY : ecs/src/registery.s

# target to generate assembly for a file
ecs/src/registery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/ecs/src/registery.cpp.s
.PHONY : ecs/src/registery.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... ecs"
	@echo "... r-type_app"
	@echo "... r-type_server"
	@echo "... Server/src/ClientState.o"
	@echo "... Server/src/ClientState.i"
	@echo "... Server/src/ClientState.s"
	@echo "... Server/src/GameLogic.o"
	@echo "... Server/src/GameLogic.i"
	@echo "... Server/src/GameLogic.s"
	@echo "... Server/src/GameServerLoop.o"
	@echo "... Server/src/GameServerLoop.i"
	@echo "... Server/src/GameServerLoop.s"
	@echo "... Server/src/GameSession.o"
	@echo "... Server/src/GameSession.i"
	@echo "... Server/src/GameSession.s"
	@echo "... Server/src/MessageQueue.o"
	@echo "... Server/src/MessageQueue.i"
	@echo "... Server/src/MessageQueue.s"
	@echo "... Server/src/Protocole.o"
	@echo "... Server/src/Protocole.i"
	@echo "... Server/src/Protocole.s"
	@echo "... Server/src/StartServer.o"
	@echo "... Server/src/StartServer.i"
	@echo "... Server/src/StartServer.s"
	@echo "... Server/src/Tcpserver.o"
	@echo "... Server/src/Tcpserver.i"
	@echo "... Server/src/Tcpserver.s"
	@echo "... Server/src/UdpProtocole.o"
	@echo "... Server/src/UdpProtocole.i"
	@echo "... Server/src/UdpProtocole.s"
	@echo "... Server/src/UdpServer.o"
	@echo "... Server/src/UdpServer.i"
	@echo "... Server/src/UdpServer.s"
	@echo "... Server/src/main.o"
	@echo "... Server/src/main.i"
	@echo "... Server/src/main.s"
	@echo "... ecs/src/registery.o"
	@echo "... ecs/src/registery.i"
	@echo "... ecs/src/registery.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

