#include "../include/key_bindings.hpp"

std::string KeyBindings::getKeyName(render::Key key) {
    switch (key) {
    case render::Key::A:
        return "A";
    case render::Key::B:
        return "B";
    case render::Key::C:
        return "C";
    case render::Key::D:
        return "D";
    case render::Key::E:
        return "E";
    case render::Key::F:
        return "F";
    case render::Key::G:
        return "G";
    case render::Key::H:
        return "H";
    case render::Key::I:
        return "I";
    case render::Key::J:
        return "J";
    case render::Key::K:
        return "K";
    case render::Key::L:
        return "L";
    case render::Key::M:
        return "M";
    case render::Key::N:
        return "N";
    case render::Key::O:
        return "O";
    case render::Key::P:
        return "P";
    case render::Key::Q:
        return "Q";
    case render::Key::R:
        return "R";
    case render::Key::S:
        return "S";
    case render::Key::T:
        return "T";
    case render::Key::U:
        return "U";
    case render::Key::V:
        return "V";
    case render::Key::W:
        return "W";
    case render::Key::X:
        return "X";
    case render::Key::Y:
        return "Y";
    case render::Key::Z:
        return "Z";
    case render::Key::Num0:
        return "0";
    case render::Key::Num1:
        return "1";
    case render::Key::Num2:
        return "2";
    case render::Key::Num3:
        return "3";
    case render::Key::Num4:
        return "4";
    case render::Key::Num5:
        return "5";
    case render::Key::Num6:
        return "6";
    case render::Key::Num7:
        return "7";
    case render::Key::Num8:
        return "8";
    case render::Key::Num9:
        return "9";
    case render::Key::Left:
        return "Left";
    case render::Key::Right:
        return "Right";
    case render::Key::Up:
        return "Up";
    case render::Key::Down:
        return "Down";
    case render::Key::Space:
        return "Space";
    case render::Key::Enter:
        return "Enter";
    case render::Key::Escape:
        return "Escape";
    case render::Key::LControl:
        return "LCtrl";
    case render::Key::RControl:
        return "RCtrl";
    case render::Key::LShift:
        return "LShift";
    case render::Key::RShift:
        return "RShift";
    case render::Key::LAlt:
        return "LAlt";
    case render::Key::RAlt:
        return "RAlt";
    case render::Key::Tab:
        return "Tab";
    case render::Key::Backspace:
        return "Backspace";
    default:
        return "Unknown";
    }
}
